#include <stdio.h>
#include <stdlib.h>
#include "dataType.h"
int main()//该主函数只供测试使用
{
    char *buffer,chartest[20]="aaatest\0",vartest[20]="aaatest\0";
    char datetest1[20]="19990108\0",datetest2[20]="1/8/1999\0",datetest3[20]="1999-01-08\0",datetest4[20]="1999-Jan-08\0",datetest5[20]="Jan-08-1999\0";
    int inttest=100,charlength=20,varlength=20;
    uint32 number=0;
    long longtest=500;
    double doubletest=5.33546;
    float floattest=2.36;
    pInt_type *int_instance;
    pChar_type *char_instance;
    pVarchar_type *varchar_instance;
    pLongint_type *longint_instance;
    pFloat_type *float_instance;
    pDouble_type *double_instance;
    pDate_type *date_instance;
    buffer=(char*)vmalloc(sizeof(char)*100);
    memset(buffer,'\0',100);
    int_instance=iniTypeInt(inttest);
    intMem2Disk(int_instance,buffer);
	//int_instance=iniTypeInt(inttest);
    intDisk2Mem(buffer,&number);
    printf("%d\n",number);
    memset(buffer,'\0',100);
    char_instance=iniTypeChar(chartest,20);
    charMem2Disk(char_instance,buffer);
	//char_instance=iniTypeChar(chartest,20);
    charDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    varchar_instance=iniTypeVarchar(vartest,20);
    varcharMem2Disk(varchar_instance,buffer);
	//varchar_instance=iniTypeVarchar(vartest,20);
    varcharDisk2Mem(buffer,&number);
    printf("%d\n",number);
    memset(buffer,'\0',100);
    longint_instance=iniTypeLong(longtest);
    longMem2Disk(longint_instance,buffer);
	//longint_instance=iniTypeLong(longtest);
    longDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    float_instance=iniTypeFloat(floattest);
    floatMem2Disk(float_instance,buffer);
	//float_instance=iniTypeFloat(floattest);
   floatDisk2Mem(buffer,&number);
    printf("%d\n",number);
    memset(buffer,'\0',100);
    double_instance=iniTypeDouble(doubletest);
    doubleMem2Disk(double_instance,buffer);
	//double_instance=iniTypeDouble(doubletest);
    doubleDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    date_instance=iniTypeDate(datetest1);
    dateMem2Disk(date_instance,buffer);
	//date_instance=iniTypeDate(datetest1);
    dateDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    date_instance=iniTypeDate(datetest2);
    dateMem2Disk(date_instance,buffer);
	//date_instance=iniTypeDate(datetest2);
    dateDisk2Mem(buffer,&number);
  printf("%d\n",number);
    memset(buffer,'\0',100);
    date_instance=iniTypeDate(datetest3);
    dateMem2Disk(date_instance,buffer);
	//date_instance=iniTypeDate(datetest3);
    dateDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    date_instance=iniTypeDate(datetest4);
    dateMem2Disk(date_instance,buffer);
	//date_instance=iniTypeDate(datetest4);
    dateDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    date_instance=iniTypeDate(datetest5);
    dateMem2Disk(date_instance,buffer);
	//date_instance=iniTypeDate(datetest5);
    dateDisk2Mem(buffer,&number);
     printf("%d\n",number);
    memset(buffer,'\0',100);
    vfree((void**)&buffer);
    return 0;
}

